# Generated by Django 4.1.2 on 2022-12-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("postcard", "0010_alter_postcard_image_alter_series_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="POI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("urls", models.ManyToManyField(null=True, to="postcard.url")),
            ],
        ),
    ]
