# Generated by Django 4.1.2 on 2022-12-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcard", "0010_alter_postcard_image_alter_series_logo"),
        ("poi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poi",
            name="urls",
            field=models.ManyToManyField(blank=True, null=True, to="postcard.url"),
        ),
    ]
