# Generated by Django 4.1.2 on 2022-12-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcard", "0011_postcard_poi"),
        ("poi", "0002_alter_poi_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poi",
            name="urls",
            field=models.ManyToManyField(
                blank=True, related_name="poi", to="postcard.url"
            ),
        ),
    ]
