# Generated by Django 2.2.7 on 2019-11-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("copyrighter", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="holder", name="url", field=models.URLField(blank=True)
        )
    ]
