# Generated by Django 2.2.7 on 2019-11-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copyrighter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyright',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='copyrighter.Licence'),
        ),
    ]
