# Generated by Django 2.2.7 on 2019-11-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrighter', '0002_copyright_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
