# Generated by Django 2.2.10 on 2020-05-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("copyrighter", "0002_holder_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="copyright",
            options={"ordering": ["holder"]},
        ),
    ]
