# Generated by Django 2.2.10 on 2020-05-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("copyrighter", "0003_auto_20200505_1649"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="holder",
            options={"ordering": ["name"]},
        ),
    ]
