# Generated by Django 2.2.13 on 2020-09-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrighter', '0006_copyright_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='org_name',
            field=models.CharField(
                blank=True,
                help_text=
                'Use for native writing of the name e.g. in Cyrillic.',
                max_length=100,
                null=True),
        ),
        migrations.AlterField(
            model_name='holder',
            name='name',
            field=models.CharField(
                help_text='Ust it for (transcripted) writing of name.',
                max_length=100),
        ),
    ]
