# Generated by Django 3.2 on 2021-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copyrighter", "0007_auto_20200925_2159"),
    ]

    operations = [
        migrations.AddField(
            model_name="holder",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Free text form to tell something about the the holder",
            ),
        ),
    ]
