# Generated by Django 5.0 on 2023-12-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copyrighter", "0013_holder_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holder",
            name="name",
            field=models.CharField(
                help_text="Use it for (transcripted) writing of name.", max_length=100
            ),
        ),
    ]
