# Generated by Django 2.2.7 on 2019-11-24 17:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models
import stdimage.models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copyrighter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
                ('path', models.TextField()),
                ('label', models.CharField(help_text='The name of the tag, without ancestors', max_length=255)),
                ('level', models.IntegerField(default=1, help_text='The level of the tag in the tree')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='postcard.Tag')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug', 'parent')},
            },
            bases=(tagulous.models.models.BaseTagTreeModel, models.Model),
        ),
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_short', models.CharField(default='', help_text='Short description of the card may be used as a teaser', max_length=100)),
                ('description', django_markdown.models.MarkdownField(default='', help_text='Actual description for a postcard:\n            * some story behind\n            * where came it from\n            * what to see')),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='img/postcardimages')),
                ('swapping', models.BooleanField(default=False, help_text='Whether this postcard is free for private swapping')),
                ('year_recieved', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('year_verified', models.BooleanField(default=True, help_text='Whether the year of recieving is verified')),
                ('photo_copyright', models.ManyToManyField(related_name='photo', to='copyrighter.Copyright')),
                ('print_copyright', models.ManyToManyField(related_name='print', to='copyrighter.Copyright')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=False, help_text='Enter a comma-separated tag string', to='postcard.Tag', tree=True)),
            ],
        ),
    ]
