# Generated by Django 2.2.7 on 2019-12-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("postcrossing", "0001_initial"),
        ("postcard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcard",
            name="postcrossing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="postcrossing.PCPostCard",
            ),
        )
    ]
