# Generated by Django 2.2.7 on 2019-11-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("postcard", "0002_auto_20191122_2146")]

    operations = [
        migrations.AddField(
            model_name="postcard",
            name="some_textfiled",
            field=models.CharField(default="", max_length=35000),
        )
    ]
