# Generated by Django 2.2.9 on 2019-12-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("postcard", "0002_postcard_postcrossing")]

    operations = [
        migrations.AlterModelOptions(
            name="postcard", options={"ordering": ["-id"]}
        )
    ]
