# Generated by Django 3.1.7 on 2021-03-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcard", "0003_postcard_subtitle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postcard", old_name="description_short", new_name="title"
        ),
        migrations.AlterField(
            model_name="postcard",
            name="title",
            field=models.CharField(
                default="", help_text="Title of the postcard", max_length=100
            ),
        ),
    ]
