# Generated by Django 3.1.7 on 2021-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copyrighter", "0007_auto_20200925_2159"),
        ("postcard", "0004_auto_20210320_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="publisher",
            field=models.ManyToManyField(
                blank=True, related_name="publisher", to="copyrighter.Copyright"
            ),
        ),
    ]
