# Generated by Django 2.2.7 on 2019-11-23 18:41

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [("postcard", "0004_auto_20191123_1753")]

    operations = [
        migrations.AddField(
            model_name="postcard",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True, upload_to="img/postcardimages"
            ),
        )
    ]
