# Generated by Django 2.2.10 on 2020-04-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0005_url_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='tile',
            new_name='title',
        ),
    ]
