# Generated by Django 3.2.3 on 2021-07-17 09:56

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0005_series_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, upload_to='img/series'),
        ),
    ]
