# Generated by Django 2.2.7 on 2019-11-23 21:06

from django.db import migrations, models
import django_markdown.models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [("postcard", "0005_postcard_image")]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="description",
            field=django_markdown.models.MarkdownField(
                default="",
                help_text="Actual description for a postcard:\n            * some story behind\n            * where came it from\n            * what to see",
            ),
        ),
        migrations.CreateModel(
            name="Tagulous_Postcard_skills",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        help_text="Internal counter of how many times this tag is in use",
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False,
                        help_text="Will not be deleted when the count reaches 0",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("slug",)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name="postcard",
            name="skills",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                max_count=5,
                to="postcard.Tagulous_Postcard_skills",
            ),
        ),
    ]
