# Generated by Django 3.2.6 on 2021-10-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postcard", "0007_postcard_description_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postcard",
            old_name="description_text",
            new_name="backside_description_text",
        ),
    ]
