# Generated by Django 2.2.7 on 2019-11-23 22:43

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [("postcard", "0009_auto_20191123_2203")]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                force_lowercase=False,
                help_text="Enter a comma-separated tag string",
                to="postcard.Tag",
                tree=True,
            ),
        )
    ]
