# Generated by Django 4.1.1 on 2022-09-18 18:02

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):
    dependencies = [
        ("postcard", "0009_postcard_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                upload_to="img/postcardimages",
                variations={
                    "large": (1024, 1024),
                    "medium": (600, 600),
                    "small": (300, 300),
                    "thumbnail": (150, 150, False),
                },
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="logo",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                upload_to="img/series",
                variations={
                    "large": (1024, 1024),
                    "medium": (600, 600),
                    "small": (300, 300),
                    "thumbnail": (150, 150, False),
                },
            ),
        ),
    ]
