# Generated by Django 2.2.10 on 2020-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0009_auto_20200418_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcard',
            name='published',
            field=models.BooleanField(default=False, help_text='Whether this postcard is visible.'),
        ),
    ]
