# Generated by Django 2.2.10 on 2020-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0010_postcard_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='further_information', to='postcard.URL'),
        ),
    ]
