# Generated by Django 2.2.7 on 2019-11-24 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("postcard", "0010_auto_20191123_2243")]

    operations = [
        migrations.AddField(
            model_name="postcard",
            name="publish_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        )
    ]
