# Generated by Django 4.1.2 on 2022-12-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poi", "0003_alter_poi_urls"),
        ("postcard", "0011_postcard_poi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="poi",
            field=models.ManyToManyField(blank=True, to="poi.poi"),
        ),
    ]
