# Generated by Django 2.2.7 on 2019-11-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copyrighter", "0001_initial"),
        ("postcard", "0012_remove_postcard_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcard",
            name="photo_copyright",
            field=models.ManyToManyField(
                related_name="photo", to="copyrighter.Copyright"
            ),
        ),
        migrations.AddField(
            model_name="postcard",
            name="print_copyright",
            field=models.ManyToManyField(
                related_name="print", to="copyrighter.Copyright"
            ),
        ),
    ]
