# Generated by Django 2.2.10 on 2020-05-09 22:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postcrossing', '0007_auto_20200503_1543'),
        ('postcard', '0012_auto_20200502_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='postcrossing',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='swapping',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='year_recieved',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='year_verified',
        ),
        migrations.CreateModel(
            name='PostcardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swapping', models.BooleanField(default=False, help_text='Whether this postcard is free for private swapping')),
                ('year_recieved', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('year_verified', models.BooleanField(default=True, help_text='Whether the year of recieving is verified')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_udpated', models.DateTimeField(auto_now=True)),
                ('postcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postcard.Postcard')),
                ('postcrossing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postcrossing.PCPostCard')),
            ],
        ),
    ]
