# Generated by Django 4.1.7 on 2023-06-25 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postcard", "0012_alter_postcard_poi"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="url",
            unique_together={("title", "url")},
        ),
    ]
