# Generated by Django 2.2.10 on 2020-05-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0013_auto_20200509_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcarditem',
            options={'ordering': ['id']},
        ),
    ]
