# Generated by Django 2.2.12 on 2020-05-22 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0014_auto_20200513_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcard',
            name='publishing_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 22, 16, 13, 16, 533779, tzinfo=utc), null=True),
        ),
    ]
