# Generated by Django 5.0 on 2023-12-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcard", "0014_remove_url_tags_delete_urltag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.URLField(max_length=250, verbose_name="URL"),
        ),
    ]
