# Generated by Django 2.2.12 on 2020-05-22 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0015_postcard_publishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='publishing_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
