# Generated by Django 5.0.1 on 2024-01-20 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postcard", "0015_alter_url_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="url",
            options={
                "ordering": ["title"],
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
            },
        ),
    ]
