# Generated by Django 2.2.12 on 2020-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0016_auto_20200522_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcard',
            old_name='last_udpated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='postcarditem',
            old_name='last_udpated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='postcarditem',
            old_name='year_recieved',
            new_name='year_received',
        ),
        migrations.AlterField(
            model_name='postcarditem',
            name='year_verified',
            field=models.BooleanField(default=True, help_text='Whether the year of receiving is verified'),
        ),
    ]
