# Generated by Django 5.0.1 on 2024-01-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poi", "0003_alter_poi_urls"),
        ("postcard", "0016_alter_url_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="poi",
            field=models.ManyToManyField(blank=True, to="poi.poi", verbose_name="POI"),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="urls",
            field=models.ManyToManyField(
                blank=True,
                related_name="further_information",
                to="postcard.url",
                verbose_name="URLs",
            ),
        ),
    ]
