# Generated by Django 5.0.1 on 2024-01-26 22:04

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postcard", "0017_alter_postcard_poi_alter_postcard_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                upload_to="img/postcardimages",
                variations={
                    "large": (1024, 1024),
                    "medium": (600, 600),
                    "small": (300, 300),
                    "thumbnail": (200, 200, False),
                },
            ),
        ),
    ]
