# Generated by Django 2.2.12 on 2020-05-29 18:56

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0017_auto_20200523_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', django_markdown.models.MarkdownField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='postcard',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='series_member', to='postcard.Series'),
        ),
    ]
