# Generated by Django 2.2.12 on 2020-05-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0018_auto_20200529_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['id'], 'verbose_name_plural': 'Series'},
        ),
    ]
