# Generated by Django 2.2.12 on 2020-05-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0019_auto_20200529_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['title'], 'verbose_name_plural': 'Series'},
        ),
    ]
