# Generated by Django 2.2.12 on 2020-05-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0020_auto_20200530_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['title']},
        ),
    ]
