# Generated by Django 2.2.13 on 2020-10-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0021_auto_20200530_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='series_links', to='postcard.URL'),
        ),
    ]
