# Generated by Django 2.2.17 on 2021-03-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0022_series_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Name of country', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='postcard',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, help_text='Country of origin if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='postcard.Country'),
        ),
    ]
