# Generated by Django 2.2.17 on 2021-03-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0023_auto_20210307_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
