# Generated by Django 2.2.17 on 2021-03-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0024_auto_20210307_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['iso_code'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='iso_code'
        ),

    ]
