# Generated by Django 2.2.17 on 2021-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0025_auto_20210307_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(default='', help_text='ISO of country', max_length=10),
        ),
    ]
