# Generated by Django 2.2.19 on 2021-03-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0026_auto_20210307_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='description',
            field=models.TextField(default='', help_text='Actual description for a postcard:\n            * some story behind\n            * where came it from\n            * what to see'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
