# Generated by Django 2.2.7 on 2019-12-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PCUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="The username of postcrossingg user",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PCPostCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pc_id",
                    models.CharField(
                        help_text="The Key at poscrossing",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("user", models.ManyToManyField(to="postcrossing.PCUser")),
            ],
        ),
    ]
