# Generated by Django 2.2.10 on 2020-04-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcrossing", "0002_auto_20200413_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcpostcard",
            name="pc_id",
            field=models.CharField(
                help_text="The Key at poscrossing",
                max_length=100,
                unique=True,
                verbose_name="Postcrossing ID",
            ),
        ),
    ]
