# Generated by Django 2.2.10 on 2020-04-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postcrossing", "0004_auto_20200413_1724"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pcpostcard",
            options={
                "ordering": ["-pc_id"],
                "verbose_name": "Postcrossing Card",
            },
        ),
    ]
