# Generated by Django 2.2.10 on 2020-05-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postcrossing", "0006_auto_20200413_1727"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pcpostcard",
            options={"ordering": ["pc_id"], "verbose_name": "Postcrossing Card"},
        ),
    ]
